/* SVN.committedRevision=1053049 */
var Zepto=function(){
	function L(t){return null==t?String(t):j[T.call(t)]||"object"}
	function Z(t){return"function"==L(t)}
	function $(t){return null!=t&&t==t.window}
	function _(t){return null!=t&&t.nodeType==t.DOCUMENT_NODE}
	function D(t){return"object"==L(t)}
	function R(t){return D(t)&&!$(t)&&Object.getPrototypeOf(t)==Object.prototype}
	function M(t){return"number"==typeof t.length}
	function k(t){return s.call(t,function(t){return null!=t})}
	function z(t){return t.length>0?n.fn.concat.apply([],t):t}
	function F(t){return t.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}
	function q(t){return t in f?f[t]:f[t]=new RegExp("(^|\\s)"+t+"(\\s|$)")}
	function H(t,e){return"number"!=typeof e||c[F(t)]?e:e+"px"}
	function I(t){var e,n;return u[t]||(e=a.createElement(t),a.body.appendChild(e),n=getComputedStyle(e,"").getPropertyValue("display"),e.parentNode.removeChild(e),"none"==n&&(n="block"),u[t]=n),u[t]
}
function V(t){return"children" in t?o.call(t.children):n.map(t.childNodes,function(t){return 1==t.nodeType?t:void 0})}
function U(n,i,r){for(e in i){r&&(R(i[e])||A(i[e]))?(R(i[e])&&!R(n[e])&&(n[e]={}),A(i[e])&&!A(n[e])&&(n[e]=[]),U(n[e],i[e],r)):i[e]!==t&&(n[e]=i[e])}}
function B(t,e){return null==e?n(t):n(t).filter(e)}
function J(t,e,n,i){return Z(e)?e.call(t,n,i):e}
function X(t,e,n){null==n?t.removeAttribute(e):t.setAttribute(e,n)}
function W(e,n){var i=e.className,r=i&&i.baseVal!==t;return n===t?r?i.baseVal:i:void (r?i.baseVal=n:e.className=n)}function Y(t){var e;try{return t?"true"==t||("false"==t?!1:"null"==t?null:/^0/.test(t)||isNaN(e=Number(t))?/^[\[\{]/.test(t)?n.parseJSON(t):t:e):t}catch(i){return t}}
function G(t,e){
	e(t);
	for(var n in t.childNodes){
		G(t.childNodes[n],e)}
		}
		var t,e,n,i,C,N,r=[],o=r.slice,s=r.filter,a=window.document,u={},f={},
		c={"column-count":1,
		columns:1,"font-weight":1,"line-height":1,
		opacity:1,"z-index":1,zoom:1
		},
		l=/^\s*<(\w+|!)[^>]*>/,h=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,
		p=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
		d=/^(?:body|html)$/i,
		m=/([A-Z])/g,
		g=["val","css","html","text","data","width","height","offset"],
		v=["after","prepend","before","append"],
		y=a.createElement("table"),
		x=a.createElement("tr"),
		b={tr:a.createElement("tbody"),
		tbody:y,thead:y,tfoot:y,td:x,th:x,
		"*":a.createElement("div")},w=/complete|loaded|interactive/,
		E=/^[\w-]*$/,
		j={},T=j.toString,S={},
		O=a.createElement("div"),
		P={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},
		A=Array.isArray||function(t){return t instanceof Array
};return S.matches=function(t,e){
	if(!e||!t||1!==t.nodeType){return !1}
	var n=t.webkitMatchesSelector||t.mozMatchesSelector||t.oMatchesSelector||t.matchesSelector;if(n){return n.call(t,e)}
	var i,r=t.parentNode,o=!r;return o&&(r=O).appendChild(t),i=~S.qsa(r,e).indexOf(t),o&&O.removeChild(t),i
	},
	C=function(t){return t.replace(/-+(.)?/g,
	function(t,e){return e?e.toUpperCase():""})},
	N=function(t){return s.call(t,function(e,n){return t.indexOf(e)==n})},
	S.fragment=function(e,i,r){
		var s,u,f;
		return h.test(e)&&(s=n(a.createElement(RegExp.$1))),s||(e.replace&&(e=e.replace(p,"<$1></$2>")),i===t&&(i=l.test(e)&&RegExp.$1),i in b||(i="*"),f=b[i],f.innerHTML=""+e,s=n.each(o.call(f.childNodes),function(){f.removeChild(this)})),R(r)&&(u=n(s),n.each(r,function(t,e){g.indexOf(t)>-1?u[t](e):u.attr(t,e)})),s},S.Z=function(t,e){return t=t||[],t.__proto__=n.fn,t.selector=e||"",t
},S.isZ=function(t){return t instanceof S.Z},S.init=function(e,i){var r;if(!e){return S.Z()}if("string"==typeof e){if(e=e.trim(),"<"==e[0]&&l.test(e)){r=S.fragment(e,RegExp.$1,i),e=null}else{if(i!==t){return n(i).find(e)}r=S.qsa(a,e)}}else{if(Z(e)){return n(a).ready(e)}if(S.isZ(e)){return e}if(A(e)){r=k(e)}else{if(D(e)){r=[e],e=null}else{if(l.test(e)){r=S.fragment(e.trim(),RegExp.$1,i),e=null}else{if(i!==t){return n(i).find(e)}r=S.qsa(a,e)}}}}return S.Z(r,e)},n=function(t,e){return S.init(t,e)},n.extend=function(t){var e,n=o.call(arguments,1);return"boolean"==typeof t&&(e=t,t=n.shift()),n.forEach(function(n){U(t,n,e)}),t},S.qsa=function(t,e){var n,i="#"==e[0],r=!i&&"."==e[0],s=i||r?e.slice(1):e,a=E.test(s);return _(t)&&a&&i?(n=t.getElementById(s))?[n]:[]:1!==t.nodeType&&9!==t.nodeType?[]:o.call(a&&!i?r?t.getElementsByClassName(s):t.getElementsByTagName(e):t.querySelectorAll(e))
},n.contains=function(t,e){return t!==e&&t.contains(e)},n.type=L,n.isFunction=Z,n.isWindow=$,n.isArray=A,n.isPlainObject=R,n.isEmptyObject=function(t){var e;for(e in t){return !1}return !0},n.inArray=function(t,e,n){return r.indexOf.call(e,t,n)},n.camelCase=C,n.trim=function(t){return null==t?"":String.prototype.trim.call(t)},n.uuid=0,n.support={},n.expr={},n.map=function(t,e){var n,r,o,i=[];if(M(t)){for(r=0;r<t.length;r++){n=e(t[r],r),null!=n&&i.push(n)}}else{for(o in t){n=e(t[o],o),null!=n&&i.push(n)}}return z(i)},n.each=function(t,e){var n,i;if(M(t)){for(n=0;n<t.length;n++){if(e.call(t[n],n,t[n])===!1){return t}}}else{for(i in t){if(e.call(t[i],i,t[i])===!1){return t}}}return t},n.grep=function(t,e){return s.call(t,e)},window.JSON&&(n.parseJSON=JSON.parse),n.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(t,e){j["[object "+e+"]"]=e.toLowerCase()
}),n.fn={forEach:r.forEach,reduce:r.reduce,push:r.push,sort:r.sort,indexOf:r.indexOf,concat:r.concat,map:function(t){return n(n.map(this,function(e,n){return t.call(e,n,e)}))},slice:function(){return n(o.apply(this,arguments))},ready:function(t){return w.test(a.readyState)&&a.body?t(n):a.addEventListener("DOMContentLoaded",function(){t(n)},!1),this},get:function(e){return e===t?o.call(this):this[e>=0?e:e+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(t){return r.every.call(this,function(e,n){return t.call(e,n,e)!==!1}),this},filter:function(t){return Z(t)?this.not(this.not(t)):n(s.call(this,function(e){return S.matches(e,t)}))},add:function(t,e){return n(N(this.concat(n(t,e))))
},is:function(t){return this.length>0&&S.matches(this[0],t)},not:function(e){var i=[];if(Z(e)&&e.call!==t){this.each(function(t){e.call(this,t)||i.push(this)})}else{var r="string"==typeof e?this.filter(e):M(e)&&Z(e.item)?o.call(e):n(e);this.forEach(function(t){r.indexOf(t)<0&&i.push(t)})}return n(i)},has:function(t){return this.filter(function(){return D(t)?n.contains(this,t):n(this).find(t).size()})},eq:function(t){return -1===t?this.slice(t):this.slice(t,+t+1)},first:function(){var t=this[0];return t&&!D(t)?t:n(t)},last:function(){var t=this[this.length-1];return t&&!D(t)?t:n(t)},find:function(t){var e,i=this;return e="object"==typeof t?n(t).filter(function(){var t=this;return r.some.call(i,function(e){return n.contains(e,t)})}):1==this.length?n(S.qsa(this[0],t)):this.map(function(){return S.qsa(this,t)
})},closest:function(t,e){var i=this[0],r=!1;for("object"==typeof t&&(r=n(t));i&&!(r?r.indexOf(i)>=0:S.matches(i,t));){i=i!==e&&!_(i)&&i.parentNode}return n(i)},parents:function(t){for(var e=[],i=this;i.length>0;){i=n.map(i,function(t){return(t=t.parentNode)&&!_(t)&&e.indexOf(t)<0?(e.push(t),t):void 0})}return B(e,t)},parent:function(t){return B(N(this.pluck("parentNode")),t)},children:function(t){return B(this.map(function(){return V(this)}),t)},contents:function(){return this.map(function(){return o.call(this.childNodes)})},siblings:function(t){return B(this.map(function(t,e){return s.call(V(e.parentNode),function(t){return t!==e})}),t)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(t){return n.map(this,function(e){return e[t]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display=""),"none"==getComputedStyle(this,"").getPropertyValue("display")&&(this.style.display=I(this.nodeName))
})},replaceWith:function(t){return this.before(t).remove()},wrap:function(t){var e=Z(t);if(this[0]&&!e){var i=n(t).get(0),r=i.parentNode||this.length>1}return this.each(function(o){n(this).wrapAll(e?t.call(this,o):r?i.cloneNode(!0):i)})},wrapAll:function(t){if(this[0]){n(this[0]).before(t=n(t));for(var e;(e=t.children()).length;){t=e.first()}n(t).append(this)}return this},wrapInner:function(t){var e=Z(t);return this.each(function(i){var r=n(this),o=r.contents(),s=e?t.call(this,i):t;o.length?o.wrapAll(s):r.append(s)})},unwrap:function(){return this.parent().each(function(){n(this).replaceWith(n(this).children())}),this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(e){return this.each(function(){var i=n(this);
(e===t?"none"==i.css("display"):e)?i.show():i.hide()})},prev:function(t){return n(this.pluck("previousElementSibling")).filter(t||"*")},next:function(t){return n(this.pluck("nextElementSibling")).filter(t||"*")},html:function(t){return 0===arguments.length?this.length>0?this[0].innerHTML:null:this.each(function(e){var i=this.innerHTML;n(this).empty().append(J(this,t,e,i))})},text:function(e){return 0===arguments.length?this.length>0?this[0].textContent:null:this.each(function(){this.textContent=e===t?"":""+e})},attr:function(n,i){var r;return"string"==typeof n&&i===t?0==this.length||1!==this[0].nodeType?t:"value"==n&&"INPUT"==this[0].nodeName?this.val():!(r=this[0].getAttribute(n))&&n in this[0]?this[0][n]:r:this.each(function(t){if(1===this.nodeType){if(D(n)){for(e in n){X(this,e,n[e])}}else{X(this,n,J(this,i,t,this.getAttribute(n)))
}}})},removeAttr:function(t){return this.each(function(){1===this.nodeType&&X(this,t)})},prop:function(e,n){return e=P[e]||e,n===t?this[0]&&this[0][e]:this.each(function(t){this[e]=J(this,n,t,this[e])})},data:function(e,n){var i=this.attr("data-"+e.replace(m,"-$1").toLowerCase(),n);return null!==i?Y(i):t},val:function(t){return 0===arguments.length?this[0]&&(this[0].multiple?n(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value):this.each(function(e){this.value=J(this,t,e,this.value)})},offset:function(t){if(t){return this.each(function(e){var i=n(this),r=J(this,t,e,i.offset()),o=i.offsetParent().offset(),s={top:r.top-o.top,left:r.left-o.left};"static"==i.css("position")&&(s.position="relative"),i.css(s)})}if(0==this.length){return null}var e=this[0].getBoundingClientRect();
return{left:e.left+window.pageXOffset,top:e.top+window.pageYOffset,width:Math.round(e.width),height:Math.round(e.height)}},css:function(t,i){if(arguments.length<2){var r=this[0],o=getComputedStyle(r,"");if(!r){return}if("string"==typeof t){return r.style[C(t)]||o.getPropertyValue(t)}if(A(t)){var s={};return n.each(A(t)?t:[t],function(t,e){s[e]=r.style[C(e)]||o.getPropertyValue(e)}),s}}var a="";if("string"==L(t)){i||0===i?a=F(t)+":"+H(t,i):this.each(function(){this.style.removeProperty(F(t))})}else{for(e in t){t[e]||0===t[e]?a+=F(e)+":"+H(e,t[e])+";":this.each(function(){this.style.removeProperty(F(e))})}}return this.each(function(){this.style.cssText+=";"+a})},index:function(t){return t?this.indexOf(n(t)[0]):this.parent().children().indexOf(this[0])},hasClass:function(t){return t?r.some.call(this,function(t){return this.test(W(t))
},q(t)):!1},addClass:function(t){return t?this.each(function(e){i=[];var r=W(this),o=J(this,t,e,r);o.split(/\s+/g).forEach(function(t){n(this).hasClass(t)||i.push(t)},this),i.length&&W(this,r+(r?" ":"")+i.join(" "))}):this},removeClass:function(e){return this.each(function(n){return e===t?W(this,""):(i=W(this),J(this,e,n,i).split(/\s+/g).forEach(function(t){i=i.replace(q(t)," ")}),void W(this,i.trim()))})},toggleClass:function(e,i){return e?this.each(function(r){var o=n(this),s=J(this,e,r,W(this));s.split(/\s+/g).forEach(function(e){(i===t?!o.hasClass(e):i)?o.addClass(e):o.removeClass(e)})}):this},scrollTop:function(e){if(this.length){var n="scrollTop" in this[0];return e===t?n?this[0].scrollTop:this[0].pageYOffset:this.each(n?function(){this.scrollTop=e}:function(){this.scrollTo(this.scrollX,e)
})}},scrollLeft:function(e){if(this.length){var n="scrollLeft" in this[0];return e===t?n?this[0].scrollLeft:this[0].pageXOffset:this.each(n?function(){this.scrollLeft=e}:function(){this.scrollTo(e,this.scrollY)})}},position:function(){if(this.length){var t=this[0],e=this.offsetParent(),i=this.offset(),r=d.test(e[0].nodeName)?{top:0,left:0}:e.offset();return i.top-=parseFloat(n(t).css("margin-top"))||0,i.left-=parseFloat(n(t).css("margin-left"))||0,r.top+=parseFloat(n(e[0]).css("border-top-width"))||0,r.left+=parseFloat(n(e[0]).css("border-left-width"))||0,{top:i.top-r.top,left:i.left-r.left}}},offsetParent:function(){return this.map(function(){for(var t=this.offsetParent||a.body;t&&!d.test(t.nodeName)&&"static"==n(t).css("position");){t=t.offsetParent}return t})}},n.fn.detach=n.fn.remove,["width","height"].forEach(function(e){var i=e.replace(/./,function(t){return t[0].toUpperCase()
});n.fn[e]=function(r){var o,s=this[0];return r===t?$(s)?s["inner"+i]:_(s)?s.documentElement["scroll"+i]:(o=this.offset())&&o[e]:this.each(function(t){s=n(this),s.css(e,J(this,r,t,s[e]()))})}}),v.forEach(function(t,e){var i=e%2;n.fn[t]=function(){var t,o,r=n.map(arguments,function(e){return t=L(e),"object"==t||"array"==t||null==e?e:S.fragment(e)}),s=this.length>1;return r.length<1?this:this.each(function(t,a){o=i?a:a.parentNode,a=0==e?a.nextSibling:1==e?a.firstChild:2==e?a:null,r.forEach(function(t){if(s){t=t.cloneNode(!0)}else{if(!o){return n(t).remove()}}G(o.insertBefore(t,a),function(t){null==t.nodeName||"SCRIPT"!==t.nodeName.toUpperCase()||t.type&&"text/javascript"!==t.type||t.src||window.eval.call(window,t.innerHTML)})})})},n.fn[i?t+"To":"insert"+(e?"Before":"After")]=function(e){return n(e)[t](this),this
}}),S.Z.prototype=n.fn,S.uniq=N,S.deserializeValue=Y,n.zepto=S,n}();window.Zepto=Zepto,void 0===window.$&&(window.$=Zepto),function(F){function M(a){return a._zid||(a._zid=S++)}function P(b,d,f,a){if(d=I(d),d.ns){var c=U(d.ns)}return(G[M(b)]||[]).filter(function(e){return !(!e||d.e&&e.e!=d.e||d.ns&&!c.test(e.ns)||f&&M(e.fn)!==M(f)||a&&e.sel!=a)})}function I(a){var b=(""+a).split(".");return{e:b[0],ns:b.slice(1).sort().join(" ")}}function U(a){return new RegExp("(?:^| )"+a.replace(" "," .* ?")+"(?: |$)")}function L(a,b){return a.del&&!C&&a.e in R||!!b}function Q(a){return V[a]||C&&R[a]||a}function B(m,g,b,c,p,s,l){var j=M(m),n=G[j]||(G[j]=[]);g.split(/\s/).forEach(function(d){if("ready"==d){return F(document).ready(b)}var e=I(d);e.fn=b,e.sel=p,e.e in V&&(b=function(f){var h=f.relatedTarget;return !h||h!==this&&!F.contains(this,h)?e.fn.apply(this,arguments):void 0
}),e.del=s;var a=s||b;e.proxy=function(h){if(h=N(h),!h.isImmediatePropagationStopped()){h.data=c;var f=a.apply(m,h._args==K?[h]:[h].concat(h._args));return f===!1&&(h.preventDefault(),h.stopPropagation()),f}},e.i=n.length,n.push(e),"addEventListener" in m&&m.addEventListener(Q(e.e),e.proxy,L(e,l))})}function q(b,d,g,a,c){var f=M(b);(d||"").split(/\s/).forEach(function(h){P(b,h,g,a).forEach(function(i){delete G[f][i.i],"removeEventListener" in b&&b.removeEventListener(Q(i.e),i.proxy,L(i,c))})})}function N(b,a){return(a||!b.isDefaultPrevented)&&(a||(a=b),F.each(D,function(c,e){var d=a[c];b[c]=function(){return this[e]=z,d&&d.apply(a,arguments)},b[e]=W}),(a.defaultPrevented!==K?a.defaultPrevented:"returnValue" in a?a.returnValue===!1:a.getPreventDefault&&a.getPreventDefault())&&(b.isDefaultPrevented=z)),b
}function k(b){var c,a={originalEvent:b};for(c in b){A.test(c)||b[c]===K||(a[c]=b[c])}return N(a,b)}var K,S=1,O=Array.prototype.slice,H=F.isFunction,J=function(a){return"string"==typeof a},G={},X={},C="onfocusin" in window,R={focus:"focusin",blur:"focusout"},V={mouseenter:"mouseover",mouseleave:"mouseout"};X.click=X.mousedown=X.mouseup=X.mousemove="MouseEvents",F.event={add:B,remove:q},F.proxy=function(b,c){if(H(b)){var a=function(){return b.apply(c,arguments)};return a._zid=M(b),a}if(J(c)){return F.proxy(b[c],b)}throw new TypeError("expected function")},F.fn.bind=function(a,b,c){return this.on(a,b,c)},F.fn.unbind=function(a,b){return this.off(a,b)},F.fn.one=function(b,c,d,a){return this.on(b,c,d,a,1)};var z=function(){return !0},W=function(){return !1},A=/^([A-Z]|returnValue$|layer[XY]$)/,D={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};
F.fn.delegate=function(a,b,c){return this.on(b,a,c)},F.fn.undelegate=function(a,b,c){return this.off(b,a,c)},F.fn.live=function(a,b){return F(document.body).delegate(this.selector,a,b),this},F.fn.die=function(a,b){return F(document.body).undelegate(this.selector,a,b),this},F.fn.on=function(n,j,d,g,m){var o,b,i=this;return n&&!J(n)?(F.each(n,function(a,c){i.on(a,j,d,c,m)}),i):(J(j)||H(g)||g===!1||(g=d,d=j,j=K),(H(d)||d===!1)&&(g=d,d=K),g===!1&&(g=W),i.each(function(c,a){m&&(o=function(e){return q(a,e.type,g),g.apply(this,arguments)}),j&&(b=function(f){var l,h=F(f.target).closest(j,a).get(0);return h&&h!==a?(l=F.extend(k(f),{currentTarget:h,liveFired:a}),(o||g).apply(h,[l].concat(O.call(arguments,1)))):void 0}),B(a,n,g,d,j,b||o)}))},F.fn.off=function(f,c,d){var b=this;return f&&!J(f)?(F.each(f,function(a,g){b.off(a,c,g)
}),b):(J(c)||H(d)||d===!1||(d=c,c=K),d===!1&&(d=W),b.each(function(){q(this,f,d,c)}))},F.fn.trigger=function(a,b){return a=J(a)||F.isPlainObject(a)?F.Event(a):N(a),a._args=b,this.each(function(){"dispatchEvent" in this?this.dispatchEvent(a):F(this).triggerHandler(a,b)})},F.fn.triggerHandler=function(c,d){var a,b;return this.each(function(f,e){a=k(J(c)?F.Event(c):c),a._args=d,a.target=e,F.each(P(e,c.type||c),function(g,h){return b=h.proxy(a),a.isImmediatePropagationStopped()?!1:void 0})}),b},"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(a){F.fn[a]=function(b){return b?this.bind(a,b):this.trigger(a)}}),["focus","blur"].forEach(function(a){F.fn[a]=function(b){return b?this.bind(a,b):this.each(function(){try{this[a]()
}catch(c){}}),this}}),F.Event=function(b,d){J(b)||(d=b,b=d.type);var f=document.createEvent(X[b]||"Events"),a=!0;if(d){for(var c in d){"bubbles"==c?a=!!d[c]:f[c]=d[c]}}return f.initEvent(b,a,!0),N(f)}}(Zepto),function(t){function l(e,n,i){var r=t.Event(n);return t(e).trigger(r,i),!r.isDefaultPrevented()}function h(t,e,i,r){return t.global?l(e||n,i,r):void 0}function p(e){e.global&&0===t.active++&&h(e,null,"ajaxStart")}function d(e){e.global&&!--t.active&&h(e,null,"ajaxStop")}function m(t,e){var n=e.context;return e.beforeSend.call(n,t,e)===!1||h(e,n,"ajaxBeforeSend",[t,e])===!1?!1:void h(e,n,"ajaxSend",[t,e])}function g(t,e,n,i){var r=n.context,o="success";n.success.call(r,t,o,e),i&&i.resolveWith(r,[t,o,e]),h(n,r,"ajaxSuccess",[e,n,t]),y(o,e,n)}function v(t,e,n,i,r){var o=i.context;i.error.call(o,n,e,t),r&&r.rejectWith(o,[n,e,t]),h(i,o,"ajaxError",[n,i,t||e]),y(e,n,i)
}function y(t,e,n){var i=n.context;n.complete.call(i,e,t),h(n,i,"ajaxComplete",[e,n]),d(n)}function x(){}function b(t){return t&&(t=t.split(";",2)[0]),t&&(t==f?"html":t==u?"json":s.test(t)?"script":a.test(t)&&"xml")||"text"}function w(t,e){return""==e?t:(t+"&"+e).replace(/[&?]{1,2}/,"?")}function E(e){e.processData&&e.data&&"string"!=t.type(e.data)&&(e.data=t.param(e.data,e.traditional)),!e.data||e.type&&"GET"!=e.type.toUpperCase()||(e.url=w(e.url,e.data),e.data=void 0)}function j(e,n,i,r){return t.isFunction(n)&&(r=i,i=n,n=void 0),t.isFunction(i)||(r=i,i=void 0),{url:e,data:n,success:i,dataType:r}}function S(e,n,i,r){var o,s=t.isArray(n),a=t.isPlainObject(n);t.each(n,function(n,u){o=t.type(u),r&&(n=i?r:r+"["+(a||"object"==o||"array"==o?n:"")+"]"),!r&&s?e.add(u.name,u.value):"array"==o||!i&&"object"==o?S(e,u,i,n):e.add(n,u)
})}var i,r,e=0,n=window.document,o=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,s=/^(?:text|application)\/javascript/i,a=/^(?:text|application)\/xml/i,u="application/json",f="text/html",c=/^\s*$/;t.active=0,t.ajaxJSONP=function(i,r){if(!("type" in i)){return t.ajax(i)}var f,h,o=i.jsonpCallback,s=(t.isFunction(o)?o():o)||"jsonp"+ ++e,a=n.createElement("script"),u=window[s],c=function(e){t(a).triggerHandler("error",e||"abort")},l={abort:c};return r&&r.promise(l),t(a).on("load error",function(e,n){clearTimeout(h),t(a).off().remove(),"error"!=e.type&&f?g(f[0],l,i,r):v(null,n||"error",l,i,r),window[s]=u,f&&t.isFunction(u)&&u(f[0]),u=f=void 0}),m(l,i)===!1?(c("abort"),l):(window[s]=function(){f=arguments},a.src=i.url.replace(/\?(.+)=\?/,"?$1="+s),n.head.appendChild(a),i.timeout>0&&(h=setTimeout(function(){c("timeout")
},i.timeout)),l)},t.ajaxSettings={type:"GET",beforeSend:x,success:x,error:x,complete:x,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:u,xml:"application/xml, text/xml",html:f,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0},t.ajax=function(e){var n=t.extend({},e||{}),o=t.Deferred&&t.Deferred();for(i in t.ajaxSettings){void 0===n[i]&&(n[i]=t.ajaxSettings[i])}p(n),n.crossDomain||(n.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(n.url)&&RegExp.$2!=window.location.host),n.url||(n.url=window.location.toString()),E(n),n.cache===!1&&(n.url=w(n.url,"_="+Date.now()));var s=n.dataType,a=/\?.+=\?/.test(n.url);if("jsonp"==s||a){return a||(n.url=w(n.url,n.jsonp?n.jsonp+"=?":n.jsonp===!1?"":"callback=?")),t.ajaxJSONP(n,o)
}var j,u=n.accepts[s],f={},l=function(t,e){f[t.toLowerCase()]=[t,e]},h=/^([\w-]+:)\/\//.test(n.url)?RegExp.$1:window.location.protocol,d=n.xhr(),y=d.setRequestHeader;if(o&&o.promise(d),n.crossDomain||l("X-Requested-With","XMLHttpRequest"),l("Accept",u||"*/*"),(u=n.mimeType||u)&&(u.indexOf(",")>-1&&(u=u.split(",",2)[0]),d.overrideMimeType&&d.overrideMimeType(u)),(n.contentType||n.contentType!==!1&&n.data&&"GET"!=n.type.toUpperCase())&&l("Content-Type",n.contentType||"application/x-www-form-urlencoded"),n.headers){for(r in n.headers){l(r,n.headers[r])}}if(d.setRequestHeader=l,d.onreadystatechange=function(){if(4==d.readyState){d.onreadystatechange=x,clearTimeout(j);var e,i=!1;if(d.status>=200&&d.status<300||304==d.status||0==d.status&&"file:"==h){s=s||b(n.mimeType||d.getResponseHeader("content-type")),e=d.responseText;
try{"script"==s?(1,eval)(e):"xml"==s?e=d.responseXML:"json"==s&&(e=c.test(e)?null:t.parseJSON(e))}catch(r){i=r}i?v(i,"parsererror",d,n,o):g(e,d,n,o)}else{v(d.statusText||null,d.status?"error":"abort",d,n,o)}}},m(d,n)===!1){return d.abort(),v(null,"abort",d,n,o),d}if(n.xhrFields){for(r in n.xhrFields){d[r]=n.xhrFields[r]}}var T="async" in n?n.async:!0;d.open(n.type,n.url,T,n.username,n.password);for(r in f){y.apply(d,f[r])}return n.timeout>0&&(j=setTimeout(function(){d.onreadystatechange=x,d.abort(),v(null,"timeout",d,n,o)},n.timeout)),d.send(n.data?n.data:null),d},t.get=function(){return t.ajax(j.apply(null,arguments))},t.post=function(){var e=j.apply(null,arguments);return e.type="POST",t.ajax(e)},t.getJSON=function(){var e=j.apply(null,arguments);return e.dataType="json",t.ajax(e)},t.fn.load=function(e,n,i){if(!this.length){return this
}var a,r=this,s=e.split(/\s/),u=j(e,n,i),f=u.success;return s.length>1&&(u.url=s[0],a=s[1]),u.success=function(e){r.html(a?t("<div>").html(e.replace(o,"")).find(a):e),f&&f.apply(r,arguments)},t.ajax(u),this};var T=encodeURIComponent;t.param=function(t,e){var n=[];return n.add=function(t,e){this.push(T(t)+"="+T(e))},S(n,t,e),n.join("&").replace(/%20/g,"+")}}(Zepto),function(a){a.fn.serializeArray=function(){var c,b=[];return a([].slice.call(this.get(0).elements)).each(function(){c=a(this);var d=c.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=d&&"reset"!=d&&"button"!=d&&("radio"!=d&&"checkbox"!=d||this.checked)&&b.push({name:c.attr("name"),value:c.val()})}),b},a.fn.serialize=function(){var b=[];return this.serializeArray().forEach(function(c){b.push(encodeURIComponent(c.name)+"="+encodeURIComponent(c.value))
}),b.join("&")},a.fn.submit=function(b){if(b){this.bind("submit",b)}else{if(this.length){var c=a.Event("submit");this.eq(0).trigger(c),c.isDefaultPrevented()||this.get(0).submit()}}return this}}(Zepto),function(a){"__proto__" in {}||a.extend(a.zepto,{Z:function(d,f){return d=d||[],a.extend(d,a.fn),d.selector=f||"",d.__Z=!0,d},isZ:function(d){return"array"===a.type(d)&&"__Z" in d}});try{getComputedStyle(void 0)}catch(b){var c=getComputedStyle;window.getComputedStyle=function(d){try{return c(d)}catch(f){return null}}}}(Zepto);function FastClick(f,c){var g;c=c||{};this.trackingClick=false;this.trackingClickStart=0;this.targetElement=null;this.touchStartX=0;this.touchStartY=0;this.lastTouchIdentifier=0;this.touchBoundary=c.touchBoundary||10;this.layer=f;this.tapDelay=c.tapDelay||200;if(FastClick.notNeeded(f)){return}function h(j,i){return function(){return j.apply(i,arguments)}}var b=["onMouse","onClick","onTouchStart","onTouchMove","onTouchEnd","onTouchCancel"];var e=this;for(var d=0,a=b.length;d<a;d++){e[b[d]]=h(e[b[d]],e)}if(deviceIsAndroid){f.addEventListener("mouseover",this.onMouse,true);f.addEventListener("mousedown",this.onMouse,true);f.addEventListener("mouseup",this.onMouse,true)}f.addEventListener("click",this.onClick,true);f.addEventListener("touchstart",this.onTouchStart,false);f.addEventListener("touchmove",this.onTouchMove,false);
f.addEventListener("touchend",this.onTouchEnd,false);f.addEventListener("touchcancel",this.onTouchCancel,false);if(!Event.prototype.stopImmediatePropagation){f.removeEventListener=function(j,l,i){var k=Node.prototype.removeEventListener;if(j==="click"){k.call(f,j,l.hijacked||l,i)}else{k.call(f,j,l,i)}};f.addEventListener=function(k,l,j){var i=Node.prototype.addEventListener;if(k==="click"){i.call(f,k,l.hijacked||(l.hijacked=function(m){if(!m.propagationStopped){l(m)}}),j)}else{i.call(f,k,l,j)}}}if(typeof f.onclick==="function"){g=f.onclick;f.addEventListener("click",function(i){g(i)},false);f.onclick=null}}var deviceIsAndroid=navigator.userAgent.indexOf("Android")>0;var deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent);var deviceIsIOS4=deviceIsIOS&&(/OS 4_\d(_\d)?/).test(navigator.userAgent);
var deviceIsIOSWithBadTarget=deviceIsIOS&&(/OS ([6-9]|\d{2})_\d/).test(navigator.userAgent);FastClick.prototype.needsClick=function(a){switch(a.nodeName.toLowerCase()){case"button":case"select":case"textarea":if(a.disabled){return true}break;case"input":if((deviceIsIOS&&a.type==="file")||a.disabled){return true}break;case"label":case"video":return true}return(/\bneedsclick\b/).test(a.className)};FastClick.prototype.needsFocus=function(a){switch(a.nodeName.toLowerCase()){case"textarea":return true;case"select":return !deviceIsAndroid;case"input":switch(a.type){case"button":case"checkbox":case"file":case"image":case"radio":case"submit":return false}return !a.disabled&&!a.readOnly;default:return(/\bneedsfocus\b/).test(a.className)}};FastClick.prototype.sendClick=function(b,c){var a,d;if(document.activeElement&&document.activeElement!==b){document.activeElement.blur()
}d=c.changedTouches[0];a=document.createEvent("MouseEvents");a.initMouseEvent(this.determineEventType(b),true,true,window,1,d.screenX,d.screenY,d.clientX,d.clientY,false,false,false,false,0,null);a.forwardedTouchEvent=true;b.dispatchEvent(a)};FastClick.prototype.determineEventType=function(a){if(deviceIsAndroid&&a.tagName.toLowerCase()==="select"){return"mousedown"}return"click"};FastClick.prototype.focus=function(a){var b;if(deviceIsIOS&&a.setSelectionRange&&a.type.indexOf("date")!==0&&a.type!=="time"){b=a.value.length;a.setSelectionRange(b,b)}else{a.focus()}};FastClick.prototype.updateScrollParent=function(b){var c,a;c=b.fastClickScrollParent;if(!c||!c.contains(b)){a=b;do{if(a.scrollHeight>a.offsetHeight){c=a;b.fastClickScrollParent=a;break}a=a.parentElement}while(a)}if(c){c.fastClickLastScrollTop=c.scrollTop
}};FastClick.prototype.getTargetElementFromEventTarget=function(a){if(a.nodeType===Node.TEXT_NODE){return a.parentNode}return a};FastClick.prototype.onTouchStart=function(c){var a,d,b;if(c.targetTouches.length>1){return true}a=this.getTargetElementFromEventTarget(c.target);d=c.targetTouches[0];if(deviceIsIOS){b=window.getSelection();if(b.rangeCount&&!b.isCollapsed){return true}if(!deviceIsIOS4){if(d.identifier===this.lastTouchIdentifier){c.preventDefault();return false}this.lastTouchIdentifier=d.identifier;this.updateScrollParent(a)}}this.trackingClick=true;this.trackingClickStart=c.timeStamp;this.targetElement=a;this.touchStartX=d.pageX;this.touchStartY=d.pageY;if((c.timeStamp-this.lastClickTime)<this.tapDelay){c.preventDefault()}return true};FastClick.prototype.touchHasMoved=function(a){var c=a.changedTouches[0],b=this.touchBoundary;
if(Math.abs(c.pageX-this.touchStartX)>b||Math.abs(c.pageY-this.touchStartY)>b){return true}return false};FastClick.prototype.onTouchMove=function(a){if(!this.trackingClick){return true}if(this.targetElement!==this.getTargetElementFromEventTarget(a.target)||this.touchHasMoved(a)){this.trackingClick=false;this.targetElement=null}return true};FastClick.prototype.findControl=function(a){if(a.control!==undefined){return a.control}if(a.htmlFor){return document.getElementById(a.htmlFor)}return a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};FastClick.prototype.onTouchEnd=function(c){var e,d,b,g,f,a=this.targetElement;if(!this.trackingClick){return true}if((c.timeStamp-this.lastClickTime)<this.tapDelay){this.cancelNextClick=true;return true}this.cancelNextClick=false;
this.lastClickTime=c.timeStamp;d=this.trackingClickStart;this.trackingClick=false;this.trackingClickStart=0;if(deviceIsIOSWithBadTarget){f=c.changedTouches[0];a=document.elementFromPoint(f.pageX-window.pageXOffset,f.pageY-window.pageYOffset)||a;a.fastClickScrollParent=this.targetElement.fastClickScrollParent}b=a.tagName.toLowerCase();if(b==="label"){e=this.findControl(a);if(e){this.focus(a);if(deviceIsAndroid){return false}a=e}}else{if(this.needsFocus(a)){if((c.timeStamp-d)>100||(deviceIsIOS&&window.top!==window&&b==="input")){this.targetElement=null;return false}this.focus(a);this.sendClick(a,c);if(!deviceIsIOS||b!=="select"){this.targetElement=null;c.preventDefault()}return false}}if(deviceIsIOS&&!deviceIsIOS4){g=a.fastClickScrollParent;if(g&&g.fastClickLastScrollTop!==g.scrollTop){return true
}}if(!this.needsClick(a)){c.preventDefault();this.sendClick(a,c)}return false};FastClick.prototype.onTouchCancel=function(){this.trackingClick=false;this.targetElement=null};FastClick.prototype.onMouse=function(a){if(!this.targetElement){return true}if(a.forwardedTouchEvent){return true}if(!a.cancelable){return true}if(!this.needsClick(this.targetElement)||this.cancelNextClick){if(a.stopImmediatePropagation){a.stopImmediatePropagation()}else{a.propagationStopped=true}a.stopPropagation();a.preventDefault();return false}return true};FastClick.prototype.onClick=function(a){var b;if(this.trackingClick){this.targetElement=null;this.trackingClick=false;return true}if(a.target.type==="submit"&&a.detail===0){return true}b=this.onMouse(a);if(!b){this.targetElement=null}return b};FastClick.prototype.destroy=function(){var a=this.layer;
if(deviceIsAndroid){a.removeEventListener("mouseover",this.onMouse,true);a.removeEventListener("mousedown",this.onMouse,true);a.removeEventListener("mouseup",this.onMouse,true)}a.removeEventListener("click",this.onClick,true);a.removeEventListener("touchstart",this.onTouchStart,false);a.removeEventListener("touchmove",this.onTouchMove,false);a.removeEventListener("touchend",this.onTouchEnd,false);a.removeEventListener("touchcancel",this.onTouchCancel,false)};FastClick.notNeeded=function(b){var a;var c;if(typeof window.ontouchstart==="undefined"){return true}c=+(/Chrome\/([0-9]+)/.exec(navigator.userAgent)||[,0])[1];if(c){if(deviceIsAndroid){a=document.querySelector("meta[name=viewport]");if(a){if(a.content.indexOf("user-scalable=no")!==-1){return true}if(c>31&&document.documentElement.scrollWidth<=window.outerWidth){return true
}}}else{return true}
}
if(b.style.msTouchAction==="none"){return true}return false};
FastClick.attach=function(b,a){return new FastClick(b,a)};
window.FastClick=FastClick;
var h5DetailSKU={shoppingcount:0,_popTimer:true,refreshPriceStock:function(){var a=0;if($("#landpageId").size()>0&&$("#landpageId").val()>0){var a=$("#landpageId").val();var e=0;if($("#landpage_type").size()>0){e=$("#landpage_type").val()}if(e==5){var c=$("#landpage_saleProductLimit").val();
var f=$("#landpage_limitNumPerUser").val();var d="";if(c&&c>=0&&f&&f>=0){d="每订单限购"+c+"件，每人限购"+f+"次"}else{if(c&&c>=0){d="每订单限购"+c+"件"}else{if(f&&f>=0){d="每人限购"+f+"次"}}}if(d!=""){$("#showMessage").text(d);
$("#showMessage").show()}h5DetailSKU.addCart();
$("#addcart").show();return}else{if(e==0){text="很抱歉，该区域不参加此活动。"}else{if(e==1){text="活动尚未开始，请耐心等待。"}else{if(e==2){text="很抱歉，当前活动已过期。"}else{if(e==3){text="很抱歉，参与活动的商品已售完。"}else{if(e==4){text="很抱歉，今天参与活动的商品已售完，请明日再来。"}}}}}}if(text!=""){$("#showMessage").text(text);
$("#showMessage").show()}$("#limitBuy").text("查看详情");$("#limitBuy").show();$("#limitBuy").on("click",function(){window.location.href=detailPath.idcCtxDomain+"/item/"+detailparams.pmId});return}var g=detailPath.busystockDomain;var b=g+"/restful/detail?mcsite="+1+"&provinceId="+detailparams.provinceId+"&pmId="+detailparams.pmId+"&channelId=102&callback=?";$.getJSON(b,function(h){if(h){if(typeof(h.currentPrice)=="undefined"||h.currentPrice<0){return}h5DetailSKU.priceLable(h);h5DetailSKU.splitPrice(h.currentPrice);h5DetailSKU.productSaleNumber(h);h5DetailSKU.getPMDisIdcInfo(h.currentPrice);h5DetailSKU.showLimitNum(h);if(h.currentStockNum&&h.currentStockNum>0&&detailparams.canBuy&&h.currentStockNum>=h.shoppingcount){if(h.shoppingcount>1){$("#buycount1").val(h.shoppingcount);$("#buycount").val(h.shoppingcount);
$("#buycount1").attr("min",h.shoppingcount);$("#buycount").attr("min",h.shoppingcount);h5DetailSKU.shoppingcount=h.shoppingcount;$("#addcart").text(h.shoppingcount+"件起购");$("#addcart1").text(h.shoppingcount+"件起购")}$("#addcart").show();$("#addcart1").show();h5DetailSKU.addCart()}else{$("#sellout").show();$("#sellout1").show()}}})},showLimitNum:function(b){var a="";if(b.promoteType&&b.totalLimitNum){if(b.promoteType==2){a="每人限购"+b.totalLimitNum+"件，超过以购物车结算价为准"}else{if(b.promoteType==3){a="每人限购"+b.totalLimitNum+"件，超过以购物车结算价为准"}else{if(b.promoteType==4&&b.userLimitNum){a="每人限购"+b.userLimitNum+"件，超过以购物车结算价为准"}else{if(b.promoteType==5){a="每单限购"+b.totalLimitNum+"个"}}}}}if(a!=""){$("#showMessage").html(a);$("#showMessage").show()}},priceLable:function(a){var b="价&nbsp;格";if(a.ruleType&&a.ruleType==2&&a.promoteType&&a.promoteType==4){b="1号团"
}else{if(a.currentPriceType&&a.currentPriceType==2){if(a&&a.ruleType&&a.ruleType==7){b="特卖价"}}}if(a.channelId==102){b="掌上专享价";$("#priceLabel").removeClass("pd_product-price-tag");$("#priceLabel").addClass("pd_product-price-mobile")}$("#priceLabel").html(b)},splitPrice:function(a){$("#current_price1").html("&yen;"+a);a=(a+"").split(".");if(a.length==2){$("#current_price").find(".pd_product-price-num").text(a[0]);$("#current_price").find(".pd_product-price-decimal").text("."+a[1])}else{$("#current_price").find(".pd_product-price-num").text(a[0])}},productSaleNumber:function(a){if(a.ruleType&&a.ruleType==2&&a.promoteType&&a.promoteType==4){if(a.soldNum&&a.soldNum>0){$("#saleNumber").html("已团人数："+a.soldNum+"</strong>");$("#saleNumber").show()}}else{if(parseInt($("#saleNumber").text())>0){$("#saleNumber").show()
}}},getPMDisIdcInfo:function(b){var a=detailPath.ctxDomain+"/item/getPMDisIdcInfo.do?callback=?";var c={pmId:detailparams.pmId};$.getJSON(a,c,function(d){if(d&&d.data){var i=d.data;if(i.detailPointVo){var f=i.detailPointVo;if(f.exchangePrice!=null&&f.exchangePoint!=null){if((f.totalExchangeNum==-1||f.totalExchangeNum>f.alreadyExchangeNum)&&f.isExchange){var j='<span class="pd_product-integral-buy-price">¥'+f.exchangePrice+"</span>";if(f.exchangePoint>0){j+="+"+f.exchangePoint+"积分"}$(".pd_product-integral-buy-price-box").html(j);$("#pointNum").val(f.exchangePoint);if(f.exchangePrice<b){$(".pd_product-integral-buy").show()}}}}if(b>0&&detailparams.iscoms!=1&&i.isBadgeMerchant==1){if(i.isLogin==0){$(".pd_product-medal-deals").css("display","block");return}var h=i.detailBadgeVo;if(h&&h.discount>0&&h.discount<100){var g=parseFloat(parseFloat(b*h.discount/100).toFixed(2));
$("#priceLabel").html("勋章价");h5DetailSKU.splitPrice(g)}}var e=i.promotionLabelVo;if(e&&e.labelDesc&&e.imageURL&&e.imageURL!=""){$("#promoLabel .pd_product-promo-copy-tag").html('<img src="'+e.imageURL+'">');$("#promoLabel .pd_product-promo-copy-desc").html(e.labelDesc)}}})},addCart:function(){$("#addcart,#addcart1").on("click",function(){if(!h5DetailSKU.validateProperty()){$(".property-wrapper").attr("class","property-wrapper error");return false}var f=$(this);var d=$("input[type='checkbox']");var c=0;var e=0;if(f.attr("id")=="addcart"){c=$("#buycount").val();if(d.size()>0&&d[0]!=null&&d[0].checked==true){e=$("#pointNum").val()}}else{c=$("#buycount1").val();if(d!=null&&d[1]!=null&&d[1].checked==true){e=$("#pointNum").val()}}if(c==null||c==""||c<1||c>999){h5DetailSKU.showAlert("请输入正确的购买数量");
return false}if(c<h5DetailSKU.shoppingcount){h5DetailSKU.showAlert("最低购买"+h5DetailSKU.shoppingcount+"件");return false}var a=0;if($("#landpageId").size()>0){a=$("#landpageId").val()+"_0_landingpage";e=0}addcartStatistics(detailparams.pmId);var b=new Date();$.ajax({type:"POST",url:detailPath.idcCtxDomain+"/deal/cart/buyproduct/"+detailparams.pmId+"/"+c+"?now="+b+"&needpoint="+e+"&promotionId="+a+"&merchantId="+detailparams.merchantId,data:"",dataType:"json",success:function(g){if(g.message.indexOf("登录")>0){window.location.href=detailPath.h5Passport+"/m/login_input.do"}else{if(g.message.indexOf("成功")>0){require(["common_cart"],function(h){h.refreshCart()})}h5DetailSKU.showAlert(g.message)}}})})},showAlert:function(a){if(h5DetailSKU._popTimer){h5DetailSKU._popTimer=false;$(".pd_pop-add-cart-success").text(a);
$(".pd_pop-add-cart-success").addClass("pd_pop-text_show");setTimeout(function(){h5DetailSKU._popTimer=true;$(".pd_pop-add-cart-success").removeClass("pd_pop-text_show")},1000)}},ajaxProdInstantInfo:function(){var a=detailPath.idcCtxDomain+"/item/ajaxProdInstantInfo.do?callback=?";var b={pmId:detailparams.pmId};$.ajax({type:"get",url:a,dataType:"json",data:b,success:function(c){if(c&&c.rtn_code){if(c.rtn_code==0){if(c.data){var d=c.data;if(d.insstantInfo){h5DetailSKU.detailProductTitle(d.insstantInfo)}}}}}})},detailProductTitle:function(b){if(!b){return}if(b.cnName){var a="";if(b.namePrefix){a=b.namePrefix+" "}a=a+b.cnName;$("#pd_product-title").html(a);$("#pd_product-title").attr("title",a);$(".pd_product-property-title").html(a)}},validateProperty:function(){var c=true;for(var a=0;a<attributeLength;
a++){var b="attribute_"+a;if(!$("#sku_unit #"+b+" ul li").hasClass("pd_product-property-select-item_current")){c=false;break}}return c}};window.addEventListener("load",function(){FastClick.attach(document.body)},false);


$(function(){h5DetailSKU.refreshPriceStock();h5DetailSKU.ajaxProdInstantInfo();$("#areaSelected").change(function(){var e=$("#areaSelected").val();if(e=="-1"){return}if(e==detailparams.provinceId){return}else{$.fn.cookie("userprovinceId",e,{expires:30,path:"",path:"/"});if(detailparams.iscoms==1){window.location.href=detailPath.ctxDomain+"/item/"+detailparams.pmId+"?jump="+detailparams.productId}else{window.location.href=detailPath.ctxDomain+"/item/"+detailparams.pmId}}});var o=true;(function(){var x=0,u=0,y=$(".pd_slide-image-lists"),z=y.find(".pd_slide-image-item"),w=$(".pd_slide-image-dot"),q=$(".pd_slide-image-left"),A=$(".pd_slide-image-right");var t=0,r=z.length;for(t;t<r;t++){z.eq(t).css({"-webkit-transform":"translate3d("+t+"00%, 0, 0)",transform:"translate3d("+t+"00%, 0, 0)"})
}var p=function(){var B=z.eq(x);if(B.attr("data-bgpic")){B.css("background-image","url("+B.attr("data-bgpic")+")");B.removeAttr("data-bgpic")}w.eq(x).addClass("pd_slide-image-dot_current").siblings("span").removeClass("pd_slide-image-dot_current")};p();var s=true;var v=function(B){if(s){s=false;if(B=="rl"){if((x+1)<r){x++;p();e(x)}}else{if(B=="lr"){if(x>0){x--;p();e(x)}}}setTimeout(function(){s=true},500)}};var e=function(B){y.css({"-webkit-transform":"translate3d(-"+B+"00%, 0, 0)",transform:"translate3d(-"+B+"00%, 0, 0)"})};iTouch({element:y[0],click:function(){h(x,o);$(".pd_product-wrap").css("display","none");$(".pd_product-showbox-wrap").removeClass("pd_product-showbox-wrap_hide")},move:function(F,D,E,C,B,G){F.preventDefault();if(D=="rl"&&Math.abs(E)>50){v(D)}else{if(D=="lr"&&Math.abs(E)>50){v(D)
}}}});q.on("click",function(){v("lr")});A.on("click",function(){v("rl")});$(".pd_product-medal-deals-login").on("click",function(){window.location.href=detailPath.h5Passport+"/m/login_input.do"})})();var h=function(e,A){var z=parseInt(e),x=0,B=$(".pd_product-showbox-lists"),C=B.find(".pd_product-showbox-item"),w=0,t=C.length,s=$("#js_show-num_current"),v=$("#js_show-num_sum"),r=$(".pd_product-showbox-left");$right=$(".pd_product-showbox-right");var q=function(){var D=C.eq(z);if(D.attr("data-bgpic")){D.css("background-image","url("+D.attr("data-bgpic")+")");D.removeAttr("data-bgpic")}s.text(z+1)};var u=true;var y=function(D){if(u){u=false;if(D=="rl"){if((z+1)<t){z++;q();p(z)}}else{if(D=="lr"){if(z>0){z--;q();p(z)}}}setTimeout(function(){u=true},500)}};var p=function(D){B.css({"-webkit-transform":"translate3d(-"+D+"00%, 0, 0)",transform:"translate3d(-"+D+"00%, 0, 0)"})
};iTouch({element:B[0],move:function(H,F,G,E,D,I){H.preventDefault();if(F=="rl"&&Math.abs(G)>50){y(F)}else{if(F=="lr"&&Math.abs(G)>50){y(F)}}}});r.on("click",function(){y("lr")});$right.on("click",function(){y("rl")});if(A){A=false;s.text(parseInt(z)+1);v.text(t);for(w;w<t;w++){C.eq(w).css({"-webkit-transform":"translate3d("+w+"00%, 0, 0)",transform:"translate3d("+w+"00%, 0, 0)"})}q();p(z)}};$("#js_product-showbox-back").on("click",function(){$(".pd_product-wrap").css("display","block");$(".pd_product-showbox-wrap").addClass("pd_product-showbox-wrap_hide")});var j=true;$(".pd_product-collect").on("click",function(){commonStatistics("","buttonPosition","addfav","");$.ajax({type:"POST",url:detailPath.idcCtxDomain+"/my/addmyfav/"+detailparams.productId+"/"+detailparams.merchantId+"?isSerial=true",data:"",dataType:"",success:function(e){if(e=="请先登录"||e=="用户未授权,请先登录"){window.location.href=detailPath.h5Passport+"/m/login_input.do"
}if(e=="收藏成功"||e=="重复收藏"){$(".pd_product-collect").addClass("pd_product-collect_current");$(".pd_pop-collect-success").addClass("pd_pop-text_show")}}})});var m=true;var f=$(".pd_product-integral-buy-price-box"),i=$(".pd_product-price"),b=$(".pd_product-property-buy");$(".pd_product-integral-buy-check").on("change",function(){if(m){m=false;var e=$(this);var p=$("#detailPromotion");if(e.is(":checked")){f.addClass("pd_product-integral-buy-price-box_current");i.addClass("pd_product-price_current");b.addClass("pd_product-property-buy_current");p.hide()}else{f.removeClass("pd_product-integral-buy-price-box_current");i.removeClass("pd_product-price_current");b.removeClass("pd_product-property-buy_current");p.show()}setTimeout(function(){m=true},500)}});
$(".pd_product-arguments").on("click",function(){$(".pd_product-wrap").css("display","none");

$(".pd_product-property").removeClass("pd_product-property_hide")});$(".js_product-property-back").on("click",function(){window.location.href=detailPath.ctxDomain+"/item/"+detailparams.pmId});$(".pd_product-property-select-item").on("click",function(){var t=$(this),e=t.parents(".pd_product-property-box").find(".js_product-property-val");if(!t.hasClass("pd_product-property-select-item_current")){t.addClass("pd_product-property-select-item_current").siblings("li").removeClass("pd_product-property-select-item_current");e.text(t.text())}else{t.removeClass("pd_product-property-select-item_current");e.text("");return}var u=true;for(var q=0;q<attributeLength;q++){var s="attribute_"+q;if(!$("#sku_unit #"+s+" ul li").hasClass("pd_product-property-select-item_current")){u=false;break}}if(!u){return}else{var p="";
$(".property-wrapper").attr("class","property-wrapper");for(var q=0;q<attributeLength;q++){var s="attribute_"+q;var r=$("#sku_unit #"+s+" ul").find(".pd_product-property-select-item_current").attr("attrvalueId");p+=q+"_"+r+"_"}if(attributeValuesAndPmIdMap[p]){var v=attributeValuesAndPmIdMap[p];$("#addcart1").hide();$("#sellout1").hide();detailparams.pmId=v;h5DetailSKU.ajaxProdInstantInfo();h5DetailSKU.refreshPriceStock()}else{$("#addcart1").hide();
$("#sellout1").show()}}});var a=$(".pd_product-num-wrap").find("input.pd_product-num-form");var c=null;var n=a.attr("max");var g=a.attr("min")||1;var d=$(".pd_product-num-wrap span");d.on("click",function(q){if(!$(this).hasClass("pd_product-num_disable")){var p=parseInt(a.val(),10)||1;if($(this).hasClass("pd_product-num-plus")){p++;d.prev().prev().attr("class","pd_product-num-minus");
if(n>g&&p>=n){d.attr("class","pd_product-num-plus pd_product-num_disable")}}else{if($(this).hasClass("pd_product-num-minus")){p--;$(this).next().next().attr("class","pd_product-num-plus");p<=g&&$(this).attr("class","pd_product-num-minus pd_product-num_disable")}}a.val(p)}});var l=null;a.bind("input propertychange",function(){var p=this;var e=$(p).val();a.val(e);l&&clearTimeout(l);l=setTimeout(function(){var q=Math.max(Math.min(n,e.replace(/\D/gi,"").replace(/(^0*)/,"")||1),g);$(p).val(q);if(q==n){a.next().attr("class","pd_product-num-plus pd_product-num_disable");a.prev().attr("class","pd_product-num-minus")}else{if(q<=g){a.next().attr("class","pd_product-num-plus");a.prev().attr("class","pd_product-num-minus pd_product-num_disable")}else{a.next().attr("class","pd_product-num-plus");a.prev().attr("class","pd_product-num-minus")
}}},50)}).trigger("input propertychange").blur(function(){$(this).trigger("input propertychange")});


var k=getQueryStringRegExp("tracker_u");if(k){if(k!=""){k=k+"_1";document.cookie="unionKey="+k+";expires="+expire_time_wangmeng+";domain=."+no3wUrl+";path=/"}}});(function(c){function e(l,f,h){var i;if(!h){i=function(){return true}}else{i=function(n,m){return n.hasOwnProperty(m)}}if(l!=null&&f!=null){var j,k,g;for(g in l){if(l.hasOwnProperty(g)){k=l[g];if(f===k){continue}if(k!==undefined&&i(f,g)){f[g]=k}}}return f}}function d(g){var f=function(){};f.prototype=g;return new f()}function a(h){var f={element:false,start:false,dbclick:false,click:false,move:false,hover:false,end:false,sliceEnd:false,startZoom:false,zoom:false,gesture:false,prevent:false,userSelect:false};var g=d(b);e(h,f,true);e(f,g);g.init();return g}var b={init:function(){if(!this.element){return false}this.errorRange=10;this.holdon=1000;this.clickRecord=[];this.offset=this.getOffset(this.element);if(this.userSelect){this.element.style.mozUserSelect="none";this.element.style.webkitUserSelect="none";
this.element.onselectstart=function(){return false}}var f=!!("ontouchstart" in window);if(f){this.bindtouchEvents()}else{this.bindclickEvents()}},bindtouchEvents:function(){var f=this;var g=this.element;g.addEventListener("touchstart",function(j){f.startEv=f.startEv||{};f.offset=f.getOffset(f.element);f.startEv.time=f.getTime();f.startEv.points=[];for(var l=0;l<j.targetTouches.length;l++){var h={};h.x=j.targetTouches[l].pageX;h.y=j.targetTouches[l].pageY;f.startEv.points.push(h)}if(f.startEv.points.length===1){var i=f.startEv.points[0];var k={x:i.x-f.offset.left,y:i.y-f.offset.top};f.start&&f.start.apply(f.element,[j,k.x,k.y])}else{if(f.startEv.points.length===2){f.startZoom&&f.startZoom.apply(null)}}j.stopPropagation()},false);g.addEventListener("touchmove",function(n){if(!f.startEv){return false
}n.stopPropagation();if(f.startEv.points.length>1){if(f.startEv.points.length===2){var j=f.offset.left;var p=f.offset.top;var v={x:f.startEv.points[0].x-j,y:f.startEv.points[0].y-p};var s={x:f.startEv.points[1].x-j,y:f.startEv.points[1].y-p};var o={x:n.targetTouches[0].pageX-j,y:n.targetTouches[0].pageY-p};var m={x:n.targetTouches[1].pageX-j,y:n.targetTouches[1].pageY-p};f.zoom&&f.zoom.apply(null,[n,v,s,o,m])}return false}else{f.moveEv=f.moveEv||{};f.moveLists=f.moveLists||[];var q={};q.x=n.targetTouches[0].pageX;q.y=n.targetTouches[0].pageY;if(!f.moveEv.angle){var h=f.startEv.points[0];var k=f.getAngle(h.x,q.x,h.y,q.y);if(!!f.prevent){switch(f.prevent){case"x":if(Math.abs(k)<20||Math.abs(k)>160){n.preventDefault()}break;case"y":if(Math.abs(k)>70&&Math.abs(k)<110){n.preventDefault()}break;case"all":n.preventDefault();
break}}if((k>-45)&&(k<=45)){f.moveEv.dir="lr"}if((k>135)||(k<=-135)){f.moveEv.dir="rl"}if((k>45)&&(k<=135)){f.moveEv.dir="ud"}if((k>-135)&&(k<=-45)){f.moveEv.dir="du"}f.moveEv.angle=k}var w=f.getTime();if(f.moveEv.last){var i=Math.sqrt(Math.pow(Math.abs(q.x-f.moveEv.last.x),2)+Math.pow(Math.abs(q.y-f.moveEv.last.y),2));f.speed=i/(w-f.moveEv.last.time);f.moveEv.last.time=w;f.moveEv.last.x=q.x;f.moveEv.last.y=q.y}else{f.moveEv.last={};f.moveEv.last.time=w;f.moveEv.last.x=q.x;f.moveEv.last.y=q.y}var u=q.x-f.startEv.points[0].x;var r=q.y-f.startEv.points[0].y;var l={x:q.x-f.offset.left,y:q.y-f.offset.top};f.move&&f.move.apply(g,[n,f.moveEv.dir,u,r,l.x,l.y]);f.moveLists.push({t:w,x:q.x,y:q.y})}},false);g.addEventListener("touchend",function(o){f.end&&f.end.apply(f.element,[]);if(!f.startEv){return false
}o.stopPropagation();var l=f.startEv.points[0];var k=f.getTime();if(!f.moveEv||Math.abs(f.moveEv.last.x-l.x)<f.errorRange&&Math.abs(f.moveEv.last.y-l.y)<f.errorRange){if(k-f.startEv.time<f.holdon){f.click&&f.click.apply(f.element,[o,l.x-f.offset.left,l.y-f.offset.top]);if(f.clickRecord.length>=1){var n=f.clickRecord[f.clickRecord.length-1];if(k-n.time<500&&Math.abs(l.x-n.x)<f.errorRange&&Math.abs(l.y-n.y)<f.errorRange){f.dbclick&&f.dbclick.apply(f.element,[l.x-f.offset.left,l.y-f.offset.top]);f.clickRecord=[]}}f.clickRecord.push({time:k,x:l.x,y:l.y})}}else{var m=f.moveLists.length;if(m>2){var i=f.moveLists[m-1];var h=f.moveLists[m-2];var j={};j.x=(i.x-h.x)/(i.t-h.t);j.y=(i.y-h.y)/(i.t-h.t);f.sliceEnd&&f.sliceEnd.apply(f.element,[j])}else{}}f.startEv=null;f.moveEv=null;f.moveLists=[];o.stopPropagation()
},false)},bindclickEvents:function(){var f=this,g=this.element,h=document;this.addHandler(g,"mousedown",function(j){if(j.button!==0){return false}f.startEv=f.startEv||{};f.offset=f.getOffset(f.element);f.startEv.time=f.getTime();f.startEv.points=[];var i={};if(j.pageX||j.pageY){i.x=j.pageX;i.y=j.pageY}else{i.x=j.clientX+h.body.scrollLeft+h.documentElement.scrollLeft;i.y=j.clientY+h.body.scrollTop+h.documentElement.scrollTop}f.startEv.points.push(i);var k={x:i.x-f.offset.left,y:i.y-f.offset.top};f.start&&f.start.apply(f.element,[j,k.x,k.y])},false);this.addHandler(g,"mousemove",function(n){if(!f.startEv){return false}f.moveEv=f.moveEv||{};f.moveLists=f.moveLists||[];var i={};if(n.pageX||n.pageY){i.x=n.pageX;i.y=n.pageY}else{i.x=n.clientX+h.body.scrollLeft+h.documentElement.scrollLeft;i.y=n.clientY+h.body.scrollTop+h.documentElement.scrollTop
}if(!f.moveEv.angle){var m=f.startEv.points[0];var o=f.getAngle(m.x,i.x,m.y,i.y);if((o>-45)&&(o<=45)){f.moveEv.dir="lr"}if((o>135)||(o<=-135)){f.moveEv.dir="rl"}if((o>45)&&(o<=135)){f.moveEv.dir="ud"}if((o>-135)&&(o<=-45)){f.moveEv.dir="du"}f.moveEv.angle=o}var l=f.getTime();f.moveEv.last=f.moveEv.last||{};f.moveEv.last.time=l;f.moveEv.last.x=i.x;f.moveEv.last.y=i.y;var k=i.x-f.startEv.points[0].x;var j=i.y-f.startEv.points[0].y;var p={x:i.x-f.offset.left,y:i.y-f.offset.top};f.move&&f.move.apply(g,[n,f.moveEv.dir,k,j,p.x,p.y]);f.moveLists.push({t:l,x:i.x,y:i.y})});this.addHandler(g,"mouseup",function(p){f.end&&f.end.apply(f.element,[]);if(!f.startEv){return false}var m=f.startEv.points[0];var l=f.getTime();if(!f.moveEv||Math.abs(f.moveEv.last.x-m.x)<f.errorRange&&Math.abs(f.moveEv.last.y-m.y)<f.errorRange){if(l-f.startEv.time<f.holdon){f.click&&f.click.apply(f.element,[p,m.x-f.offset.left,m.y-f.offset.top]);
if(f.clickRecord.length>=1){var o=f.clickRecord[f.clickRecord.length-1];if(l-o.time<500&&Math.abs(m.x-o.x)<f.errorRange&&Math.abs(m.y-o.y)<f.errorRange){f.dbclick&&f.dbclick.apply(f.element,[m.x-f.offset.left,m.y-f.offset.top]);f.clickRecord=[]}}f.clickRecord.push({time:l,x:m.x,y:m.y})}}else{var n=f.moveLists.length;if(n>2){var j=f.moveLists[n-1];var i=f.moveLists[n-2];var k={};k.x=(j.x-i.x)/(j.t-i.t);k.y=(j.y-i.y)/(j.t-i.t);f.sliceEnd&&f.sliceEnd.apply(f.element,[k])}else{}}f.startEv=null;f.moveEv=null;f.moveLists=[]});this.addHandler(g,"mouseout",function(i){if(f.checkHover(i,this)){f.startEv=null;f.moveEv=null;f.moveLists=[]}})},checkHover:function(g,f){if(g.type=="mouseover"){return !this.contains(f,g.relatedTarget||g.fromElement)&&!((g.relatedTarget||g.fromElement)===f)}else{return !this.contains(f,g.relatedTarget||g.toElement)&&!((g.relatedTarget||g.toElement)===f)
}},contains:function(f,g){return f.contains?f!=g&&f.contains(g):!!(f.compareDocumentPosition(g)&16)},addHandler:function(h,g,f){if(h.addEventListener){h.addEventListener(g,f,false)}else{if(h.attachEvent){h.attachEvent("on"+g,f)}}},getTime:function(){return new Date().getTime()},getAngle:function(h,g,j,i){this.pi=this.pi||Math.PI;var f=g-h;var l=i-j;var k=Math.atan2(l,f)*180/this.pi;return k},getOffset:function(i){var g=i.offsetTop;var f=i.offsetLeft;if(i.offsetParent!=null){var h=this.getOffset(i.offsetParent);g+=h.top;f+=h.left}return{top:g,left:f}}};c.iTouch=a})(window);(function(e){var d=iTouch;if(!d){return false}var a=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(k){return setTimeout(k,1)
}})();var g=(function(){return window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout})();var j=Math.PI;var b=null;function f(q,k,m){var n;if(!m){n=function(){return true}}else{n=function(s,r){return s.hasOwnProperty(r)}}if(q!=null&&k!=null){var o,p,l;for(l in q){if(q.hasOwnProperty(l)){p=q[l];if(k===p){continue}if(p!==undefined&&n(k,l)){k[l]=p}}}return k}}function i(l){var k=function(){};k.prototype=l;return new k()}function c(m){var k={outer:false,inner:false,atTop:false,spacing:false,atEnd:false,moving:false,buffer:40,fix:null,index:0,count:false,inertia:false};var l=i(h);f(m,k,true);f(k,l);l.init();return l
}var h={init:function(){var k=this;this.lastMoved=null;if(!this.outer||!this.inner){return false}this.plant=null;var l=navigator.userAgent.toLocaleLowerCase();if(l.indexOf("iphone")>-1){this.plant="iphone"}else{if(l.indexOf("android")>-1){this.plant="android"}}this.setStyle();d({element:k.outer,start:function(m){k.start(m)},move:function(q,o,p,n,m,r){k.move(q,o,p,n,m,r)},end:function(){k.end()},sliceEnd:function(m){k.sliceEnd(m)},prevent:"all",multiple:false})},sin:function(r,k,p,q,m){var n=new Date().getTime();var l=n+p;function o(){var u=new Date().getTime();var s=Math.sin((u-n)/(l-n)*j/2)*(k-r)+r;q&&q.apply(null,[s]);if(u>l){g(b);b=null;m&&m.apply(null)}else{b=a(o)}}if(!!b){g(b);b=null}b=a(o)},slowdown:function(o,k,q,m){var n=new Date().getTime();var l=(k/k)*(-0.1);t=Math.abs(k/l);function p(){var s=new Date().getTime();
var u=(s-n);var r=o+(2*k+l*u)*u/2;q&&q.apply(null,[r]);if(s-n>t){g(b);b=null;m&&m.apply(null)}else{b=a(p)}}if(!!b){g(b);b=null}b=a(p)},setStyle:function(){var k=this.inner,l=this.outer,m=this.prefix;l.style.overflow="hidden";l.style.position=l.style.position?l.style.position:"relative";k.style.webkitTransformStyle="preserve-3d";k.style.webkitTransform="translateX(0)"},start:function(k){this.touchstartX=parseFloat(this.inner.style.webkitTransform.replace("translateX(",""));this.movedDis=0},move:function(l,k,q,p,n,m){var s=this.inner.clientWidth;var o=this.outer.clientWidth;if(s<o){return false}if(this.touchstartX==null){this.start();this.movedDis=q;return}var r=q-this.movedDis+this.touchstartX;this.move2Pos(r)},end:function(){this.movedDis=0;this.touchstartX=null;this.lastMoved=null;var s=this.inner.clientWidth;
var r=this.outer.clientWidth;if(s<r){return false}var u=this;var l=this.buffer;var q=parseFloat(this.inner.style.webkitTransform.replace("translateX(",""));var s=this.inner.clientWidth;var r=this.outer.clientWidth;var o=-s+r;if(q>0){u.sin(q,0,200,function(n){u.move2Pos(n)},function(){u.move2Pos(0);u.atTop&&u.atTop.apply(null);if(!!u.fix){u.index=0;u.count&&u.count.apply(null,[u.index])}})}else{if(q<o){u.sin(q,o,200,function(n){u.move2Pos(n)},function(){u.move2Pos(o);u.atEnd&&u.atEnd.apply(null);if(!!u.fix){u.index=~~(Math.abs(o)/u.fix);u.count&&u.count.apply(null,[u.index])}})}else{if(!!this.fix){var m=Math.abs(q);var p=this.fix;var k=~~(m/p);if((m%p)>(p*0.5)){k++}u.sin(q,-p*k,200,function(n){u.move2Pos(n)},function(){u.index=k;u.move2Pos(-p*k);u.count&&u.count.apply(null,[u.index])})}}}},sliceEnd:function(q){var s=this.inner.clientWidth;
var p=this.outer.clientWidth;if(s<p){return false}var u=this;var k=q.x;var r=Math.abs(q.x);var n=parseFloat(this.inner.style.webkitTransform.replace("translateX(",""));var l=Math.abs();if(!!this.fix&&r>1){var o=this.index-k/r;if(o<0||o>=~~(s/u.fix)){return false}var m=-(o*this.fix);u.sin(n,m,200,function(v){u.move2Pos(v)},function(){u.move2Pos(m);u.index=o;u.count&&u.count.apply(null,[u.index])})}if(this.inertia&&r>1){u.slowdown(n,k,function(v){u.move2Pos(v)})}},move2Pos:function(k,o){if(o==undefined){o=true}var m=o?this.buffer:0;if(k>m){k=m}var n=this.inner.clientWidth;var p=this.outer.clientWidth;var l=-n+p-m;if(k<l){k=l}this.moving&&this.moving.apply(null,[Math.abs(k)]);this.inner.style.webkitTransform="translateX("+k+"px)"}};e.iTouch=iTouch})(window);$(function(){var detailPromotion=function(){var landpageId=detailparams.landpageId;if(landpageId>0){return false}var pmId=detailparams.pmId;var provinceId=detailparams.provinceId;var productId=detailparams.productId;var merchantId=detailparams.merchantId;var url=detailPath.ctxDomain+"/item/getPMPromotion.do?";var detailPromotion=$("#detailPromotion");var params={pmId:detailparams.pmId,provinceId:provinceId};$.ajax({type:"get",url:url,dataType:"json",data:params,success:function(data){if(data&&data.rtn_code==0){var datas=data.data;for(var i=0;i<datas.length;i++){var promotionData=datas[i];var promotionType="";var html="";var promotionId=promotionData.promotionId;var promotionLevelId=promotionData.id;var description=promotionData.description;if(promotionData.promotionType==1){promotionType="满减";
html="<a href="+detailPath.ctxDomain+"/search/p"+promotionId+"-pl"+promotionLevelId+"-p1-s1?productId="+productId+"&merchantId="+merchantId+' class="pd_promotions-item"><span class="pd_promotions-status pd_promotions-status-sale">'}if(promotionData.promotionType==2){promotionType="优惠";html="<a href="+detailPath.ctxDomain+"/search/n"+promotionId+"-pl"+promotionLevelId+"-p1?productId="+productId+"&merchantId="+merchantId+' class="pd_promotions-item"><span class="pd_promotions-status pd_promotions-status-preferential">'}if(promotionData.promotionType==3){promotionType="满折";html="<a href="+detailPath.ctxDomain+"/search/p"+promotionId+"-pl"+promotionLevelId+"-p1-s1?productId="+productId+"&merchantId="+merchantId+' class="pd_promotions-item"><span class="pd_promotions-status pd_promotions-status-discount">'
}if(promotionData.promotionType==4){promotionType="满赠";html="<a href="+detailPath.ctxDomain+"/search/p"+promotionId+"-pl"+promotionLevelId+"-p1-s1?productId="+productId+"&merchantId="+merchantId+' class="pd_promotions-item"><span class="pd_promotions-status pd_promotions-status-send">'}if(promotionData.promotionType==5){promotionType="换购";html="<a href="+detailPath.ctxDomain+"/search/p"+promotionId+"-pl"+promotionLevelId+"-p1-s1?productId="+productId+"&merchantId="+merchantId+' class="pd_promotions-item"><span class="pd_promotions-status pd_promotions-status-change">'}html+=promotionType+'</span><span class="pd_promotions-title">'+description+"</span></a>";detailPromotion.append(html)}}}})};var ajaxGetMoreInterestedProducts=function(){var provinceId=detailparams.provinceId;var productid=detailparams.productId;
var merchantId=detailparams.merchantId;var pmId=detailparams.pmId;var prodId=detailparams.productId;var params={pmId:detailparams.pmId,provinceId:provinceId,productId:prodId,merchantId:merchantId};var url=detailPath.idcCtxDomain+"/item/ajaxGetMoreInterestedProducts.do?";$.ajax({type:"get",url:url,dataType:"json",data:params,success:function(rev){if(rev.data){var info=rev.data;if(info.products){var products=eval("("+info.products+")").data;var pmsArray=new Array();if(products.length>0){pmsArray.push('<h3 class="pd_buy-also-look-title"><span class="pd_buy-also-look-title-text">买过该商品的还看过</span></h3>');pmsArray.push('<div class="pd_buy-also-look-wrap"><div class="pd_buy-also-look-lists">');for(var index=0;index<products.length;index++){var record=products[index];pmsArray.push('<a href="'+detailPath.ctxDomain+"/item/"+record.pmId+'" class="pd_buy-also-look-product">');
pmsArray.push('<span class="pd_buy-also-look-product-pic" style="background-image:url('+record.pic_url+');"></span>');pmsArray.push('<strong class="pd_buy-also-look-product-price">&yen;'+record.common_price+"</strong>");pmsArray.push('<span class="pd_buy-also-look-product-title">'+record.productCName+"</span></a>")}pmsArray.push('</div"></div>');$("#pd_buy-also-look").html(pmsArray.join(""))}}}}})};var getCookie=function(name){var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");if(arr=document.cookie.match(reg)){return(arr[2])}else{return""}};var pid=detailparams.productId;var saveBrowsingpro=function(){var shistory="";var arrhistory="";if(window.localStorage.getItem("browsinghistory")!=null){shistory=window.localStorage.getItem("browsinghistory");arrhistory=window.localStorage.getItem("browsinghistory").split("|")
}else{if(getCookie("browsinghistory")!=null){shistory=getCookie("browsinghistory");arrhistory=getCookie("browsinghistory").split("|")}}var isdiff=0;if(arrhistory!=""&&arrhistory.length>0){$.each(arrhistory,function(index,item){if(pid==item){isdiff=1}})}if(isdiff==0){if(arrhistory!=""&&arrhistory.length==100){arrhistory.splice(0,1);shistory=arrhistory.join("|");shistory+="|"+pid}else{if(arrhistory.length<1){shistory+=pid}else{shistory+="|"+pid}}window.localStorage.setItem("browsinghistory",shistory)}};detailPromotion();ajaxGetMoreInterestedProducts();saveBrowsingpro()});